"""
SecureUSB Version Information
Auto-generated by CI/CD pipeline
"""

# Version components
VERSION_MAJOR = 0
VERSION_MINOR = 1
VERSION_PATCH = 0

# Build information (set by CI/CD)
BUILD_TIMESTAMP = "development"
BUILD_COMMIT = "unknown"
BUILD_NUMBER = "0"

def get_version():
    """Get the semantic version string"""
    return f"{VERSION_MAJOR}.{VERSION_MINOR}.{VERSION_PATCH}"

def get_full_version():
    """Get the full version with build info"""
    return f"{get_version()}+{BUILD_NUMBER}"

def get_version_info():
    """Get complete version information as a dict"""
    return {
        "version": get_version(),
        "full_version": get_full_version(),
        "build_timestamp": BUILD_TIMESTAMP,
        "build_commit": BUILD_COMMIT,
        "build_number": BUILD_NUMBER,
    }

__version__ = get_version()
__build__ = get_full_version()
